import { Column } from "material-table";

// (Columas das tabelas: Mapeamento)
export const Columns = [
  { title: "Evento", field: "event" },
  { title: "Nome", field: "name" },
  { title: "Delegação", field: "delegation" },
  { title: "Comissário", field: "commissioner" },
  { title: "Acompanhante", field: "partner" },
  { title: "Sexo", field: "sex" },
  { title: "Hotel", field: "hotel" },
  { title: "Tipo de Quarto", field: "room_type" },
  { title: "Festa", field: "party" },
  { title: "Gestão Festa", field: "party_management" },
  { title: "Outros", field: "others" },
  { title: "Gestão Outros", field: "other_management" },
  { title: "Cidade", field: "city" },
  { title: "Estado", field: "state" },
  { title: "Situação Final", field: "final_status" },
  { title: "Status Compras", field: "purchase_status" },
  { title: "Gestão Inadimplentes", field: "non_payment_management" },
  { title: "Vencidos", field: "due" },
  { title: "CPF", field: "cpf" },
  { title: "Email", field: "email" },
  { title: "Facebook", field: "facebook" },
  { title: "Instagram", field: "instagram" },
  { title: "DDD", field: "phone_ddd" },
  { title: "Telefone", field: "phone_number" },
  { title: "DDD", field: "mobile_ddd" },
  { title: "Telefone", field: "mobile_number" },
];
